language: python
python: 3.6

install:
    - pip install tox

before_script:
  # Disable IPv6. Ref travis-ci/travis-ci#8711
  - echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6

script:
    - tox -e py36
