swagger: "2.0"
info:
  title: Storytellers Reactions Service
  description: provides functionalities for Storytellers Reactions
  license:
    name: APLv2
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.1.0
basePath: /stories
paths: 
  /{storyid}/react:
    post:
      operationId: post_story_react
      description: post a reaction to the story identified by 'storyid'
      parameters:
        - name: storyid
          in: path
          description: ID of the story to react to
          required: true
          schema:
            type: integer
      consumes:
      - application/json
      produces:
      - application/json
      requestBody:
        description: value of the reaction
        required: true
        content:
          application/x-www-form-urlencoded::
            schema:
              type: object
              properties:
                like:
                  type: string
      responses:
        '200':
          description: Reaction posted successfully
          content: 
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: feedback message
        '400':
          description: Reaction not posted
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    error:
                      type: string
                      description: error message 