openapi: 3.0.0
info:
  title: Storytellers Reactions Service
  description: Provides functionalities for Storytellers Reactions
  license:
    name: APLv2
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
  version: "1.0.0-oas3"
paths:
  '/stories/{storyid}/react':
    post:
      security: 
        - csrf_access_token: []
      operationId: post_story_react
      description: post a reaction to the story identified by 'storyid'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                react:
                  type: string
                  example: 'like'
      parameters:
        - name: storyid
          in: path
          description: ID of the story to react to
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Reaction posted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: feedback message
        '400':
          description: Reaction not posted
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: error message

components:
  
  securitySchemes:
    csrf_access_token: 
      type: http
      scheme: bearer
      bearerFormat: JWT